CREATE TABLE
  IF NOT EXISTS core.systems (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE -- e.g. 'dnd5e', 'pathfinder2'
  );

CREATE TABLE
  IF NOT EXISTS core.tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    color VARCHAR(7) DEFAULT '#777777',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

INSERT INTO core.systems (name) VALUES 
    ('dnd5e')
ON DUPLICATE KEY UPDATE name = VALUES(name);